# Generated by Django 3.2.6 on 2021-11-18 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_location'),
        ('projects', '0006_auto_20211111_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='projects',
            new_name='project',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('owner', 'project')},
        ),
    ]
