# Generated by Django 3.2.6 on 2021-11-22 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_project_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Tags',
            new_name='tags',
        ),
    ]
